# Written by Emmanuel Butor
# used to compile the test binaries

# Usage: run "make" to compile all of the test files
#        run "make clean" to delete the binary files

CSTANDARD = -std=c99

all:
	gcc -o test-simple $(CSTANDARD) ../src/dymat.c test-simple.c

clean:
	rm test-simple
